In [1]:
# Import libraries
import pandas as pd
import os

# Define file paths and load data
data_path = "../unprocessed-data"
season_file = "nba_player_stats_2023-24.csv" # 23-24 season for intial testing
file_path = os.path.join(data_path, season_file)
season_data = pd.read_csv(file_path)

pd.set_option('display.max_columns', None)
season_data.head() # Test successful load

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season
0,Joel Embiid,29.0,PHI,C,39.0,39.0,33.6,11.5,21.8,0.529,1.4,3.6,0.388,10.2,18.3,0.556,0.561,10.2,11.6,0.883,2.4,8.6,11.0,5.6,1.2,1.7,3.8,2.9,34.7,AS,2023-24
1,Luka Dončić,24.0,DAL,PG,70.0,70.0,37.5,11.5,23.6,0.487,4.1,10.6,0.382,7.4,13.0,0.573,0.573,6.8,8.7,0.786,0.8,8.4,9.2,9.8,1.4,0.5,4.0,2.1,33.9,"MVP-3,CPOY-6,AS,NBA1",2023-24
2,Giannis Antetokounmpo,29.0,MIL,PF,73.0,73.0,35.2,11.5,18.8,0.611,0.5,1.7,0.274,11.0,17.1,0.645,0.624,7.0,10.7,0.657,2.7,8.8,11.5,6.5,1.2,1.1,3.4,2.9,30.4,"MVP-4,DPOY-9,CPOY-12,AS,NBA1",2023-24
3,Shai Gilgeous-Alexander,25.0,OKC,PG,75.0,75.0,34.0,10.6,19.8,0.535,1.3,3.6,0.353,9.3,16.2,0.576,0.567,7.6,8.7,0.874,0.9,4.7,5.5,6.2,2.0,0.9,2.2,2.5,30.1,"MVP-2,DPOY-7,CPOY-3,AS,NBA1",2023-24
4,Jalen Brunson,27.0,NYK,PG,77.0,77.0,35.4,10.3,21.4,0.479,2.7,6.8,0.401,7.5,14.6,0.516,0.543,5.5,6.5,0.847,0.6,3.1,3.6,6.7,0.9,0.2,2.4,1.9,28.7,"MVP-5,CPOY-5,AS,NBA2",2023-24

In [2]:
# Combine season data into a single data structure
season_files = [file for file in os.listdir(data_path) if file.endswith('.csv')]
all_season_data = []

# Iterate through datasets and concatenate
for season_data_file in season_files:
    file_path = os.path.join(data_path, season_data_file)
    season_df = pd.read_csv(file_path)  # Renamed variable to avoid conflict
    all_season_data.append(season_df)

# Concatenate all the dataframes into one large dataframe
combined_data = pd.concat(all_season_data, ignore_index=True)

# Display the first/last few rows of the combined dataset
combined_data

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season
0,Adrian Dantley,25.0,UTA,SF,80.0,NaN,42.7,11.4,20.3,0.559,0.0,0.1,0.286,11.3,20.3,0.560,0.559,7.9,9.8,0.806,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,"MVP-12,AS,NBA2",1980-81
1,Moses Malone,25.0,HOU,C,80.0,NaN,40.6,10.1,19.3,0.522,0.0,0.0,0.333,10.1,19.3,0.522,0.522,7.6,10.1,0.757,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,"MVP-4,AS,NBA2",1980-81
2,George Gervin,28.0,SAS,SG,82.0,82.0,33.7,10.4,21.1,0.492,0.1,0.4,0.257,10.3,20.7,0.496,0.494,6.2,7.6,0.826,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,"MVP-5,AS,NBA1",1980-81
3,Kareem Abdul-Jabbar,33.0,LAL,C,80.0,NaN,37.2,10.5,18.2,0.574,0.0,0.0,0.000,10.5,18.2,0.574,0.574,5.3,6.9,0.766,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,"MVP-3,AS,NBA1",1980-81
4,David Thompson,26.0,DEN,SG,77.0,NaN,34.0,9.5,18.8,0.506,0.1,0.5,0.256,9.4,18.3,0.513,0.509,6.4,8.0,0.795,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,NaN,1980-81
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24060,Justin Minaya,25.0,POR,SF,1.0,0.0,6.0,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,0.0,0.0,NaN,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,2024-25
24061,Riley Minix,24.0,SAS,SF,1.0,0.0,7.0,0.0,1.0,0.000,0.0,1.0,0.000,0.0,0.0,NaN,0.000,0.0,0.0,NaN,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024-25
24062,Jalen Pickett,25.0,DEN,SG,2.0,0.0,2.0,0.0,0.5,0.000,0.0,0.5,0.000,0.0,0.0,NaN,0.000,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,2024-25
24063,Cole Swider,25.0,DET,SF,2.0,0.0,6.5,0.0,2.5,0.000,0.0,2.5,0.000,0.0,0.0,NaN,0.000,0.0,0.0,NaN,0.0,1.0,1.0,0.5,0.0,0.0,0.0,0.5,0.0,NaN,2024-25
24064,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.464,NaN,NaN,0.359,NaN,NaN,0.541,0.540,NaN,NaN,0.777,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024-25

In [3]:
# Show empty values in combined data
combined_data.isnull().sum()

Player        0
Age          45
Team         45
Pos          45
G            45
GS          345
MP           45
FG           45
FGA          45
FG%         130
3P           45
3PA          45
3P%        3793
2P           45
2PA          45
2P%         226
eFG%        130
FT           45
FTA          45
FT%        1154
ORB          45
DRB          45
TRB          45
AST          45
STL          45
BLK          45
TOV          45
PF           45
PTS          45
Awards    21821
Season        0
dtype: int64

In [4]:
# Calculate percentages from the raw values
combined_data['FG%'] = (combined_data['FG'] / combined_data['FGA']) * 100
combined_data['3P%'] = (combined_data['3P'] / combined_data['3PA']) * 100
combined_data['2P%'] = (combined_data['2P'] / combined_data['2PA']) * 100
combined_data['FT%'] = (combined_data['FT'] / combined_data['FTA']) * 100

# Calculate eFG% (Effective Field Goal Percentage)
combined_data['eFG%'] = ((combined_data['FG'] + 0.5 * combined_data['3P']) / combined_data['FGA']) * 100

# Handle division by zero (replace NaN values with 0 or another value)
combined_data['FG%'].fillna(0, inplace=True)
combined_data['3P%'].fillna(0, inplace=True)
combined_data['2P%'].fillna(0, inplace=True)
combined_data['FT%'].fillna(0, inplace=True)
combined_data['eFG%'].fillna(0, inplace=True)

# Show updated empty values in combined data
combined_data.isnull().sum()

Player        0
Age          45
Team         45
Pos          45
G            45
GS          345
MP           45
FG           45
FGA          45
FG%           0
3P           45
3PA          45
3P%           0
2P           45
2PA          45
2P%           0
eFG%          0
FT           45
FTA          45
FT%           0
ORB          45
DRB          45
TRB          45
AST          45
STL          45
BLK          45
TOV          45
PF           45
PTS          45
Awards    21821
Season        0
dtype: int64

In [5]:
# Drop lines representing 'League Average'
combined_data = combined_data[combined_data['Player'] != 'League Average']

# Show updated empty values in combined data
combined_data.isnull().sum()

Player        0
Age           0
Team          0
Pos           0
G             0
GS          300
MP            0
FG            0
FGA           0
FG%           0
3P            0
3PA           0
3P%           0
2P            0
2PA           0
2P%           0
eFG%          0
FT            0
FTA           0
FT%           0
ORB           0
DRB           0
TRB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
Awards    21776
Season        0
dtype: int64

In [6]:
# Most NaN for GS come from players in the 1980-81 season, add 0 values since data is from long ago
combined_data['GS'] = combined_data['GS'].fillna(0)

# Add 'No Award' value for 'Awards' column where Awards is NaN
combined_data.loc[combined_data['Awards'].isna(), 'Awards'] = "No Awards"

# Show updated empty values in combined data
combined_data.isnull().sum()

C:\Users\James Crespo\AppData\Local\Temp\ipykernel_6568\1117744735.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_data['GS'] = combined_data['GS'].fillna(0)

Player    0
Age       0
Team      0
Pos       0
G         0
GS        0
MP        0
FG        0
FGA       0
FG%       0
3P        0
3PA       0
3P%       0
2P        0
2PA       0
2P%       0
eFG%      0
FT        0
FTA       0
FT%       0
ORB       0
DRB       0
TRB       0
AST       0
STL       0
BLK       0
TOV       0
PF        0
PTS       0
Awards    0
Season    0
dtype: int64

In [7]:
# Add TS% column to the combined dataset
combined_data['TS%'] = combined_data.apply(
    lambda row: (row['PTS'] / (2 * (row['FGA'] + 0.44 * row['FTA'])) * 100)
    if (row['FGA'] + 0.44 * row['FTA']) > 0 else 0, axis=1
)

# Display the updated DataFrame
combined_data.head()

C:\Users\James Crespo\AppData\Local\Temp\ipykernel_6568\1277164970.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_data['TS%'] = combined_data.apply(

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season,TS%
0,Adrian Dantley,25.0,UTA,SF,80.0,0.0,42.7,11.4,20.3,56.157635,0.0,0.1,0.0,11.3,20.3,55.665025,56.157635,7.9,9.8,80.612245,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,"MVP-12,AS,NBA2",1980-81,62.367951
1,Moses Malone,25.0,HOU,C,80.0,0.0,40.6,10.1,19.3,52.331606,0.0,0.0,0.0,10.1,19.3,52.331606,52.331606,7.6,10.1,75.247525,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,"MVP-4,AS,NBA2",1980-81,58.541105
2,George Gervin,28.0,SAS,SG,82.0,82.0,33.7,10.4,21.1,49.289100,0.1,0.4,25.0,10.3,20.7,49.758454,49.526066,6.2,7.6,81.578947,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,"MVP-5,AS,NBA1",1980-81,55.432826
3,Kareem Abdul-Jabbar,33.0,LAL,C,80.0,0.0,37.2,10.5,18.2,57.692308,0.0,0.0,0.0,10.5,18.2,57.692308,57.692308,5.3,6.9,76.811594,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,"MVP-3,AS,NBA1",1980-81,61.687700
4,David Thompson,26.0,DEN,SG,77.0,0.0,34.0,9.5,18.8,50.531915,0.1,0.5,20.0,9.4,18.3,51.366120,50.797872,6.4,8.0,80.000000,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,No Awards,1980-81,57.123656

In [8]:
# Add EFF column to the combined dataset
combined_data['EFF'] = combined_data.apply(
    lambda row: (
        (row['PTS'] + row['TRB'] + row['AST'] + row['STL'] + row['BLK'] -
         (row['FGA'] - row['FG']) - (row['FTA'] - row['FT']) - row['TOV']) / row['G'] * 100
    ) if row['G'] > 0 else 0, axis=1
)

# Display the updated DataFrame
combined_data.head()

C:\Users\James Crespo\AppData\Local\Temp\ipykernel_6568\4052313130.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_data['EFF'] = combined_data.apply(

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season,TS%,EFF
0,Adrian Dantley,25.0,UTA,SF,80.0,0.0,42.7,11.4,20.3,56.157635,0.0,0.1,0.0,11.3,20.3,55.665025,56.157635,7.9,9.8,80.612245,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,"MVP-12,AS,NBA2",1980-81,62.367951,35.500000
1,Moses Malone,25.0,HOU,C,80.0,0.0,40.6,10.1,19.3,52.331606,0.0,0.0,0.0,10.1,19.3,52.331606,52.331606,7.6,10.1,75.247525,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,"MVP-4,AS,NBA2",1980-81,58.541105,39.625000
2,George Gervin,28.0,SAS,SG,82.0,82.0,33.7,10.4,21.1,49.289100,0.1,0.4,25.0,10.3,20.7,49.758454,49.526066,6.2,7.6,81.578947,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,"MVP-5,AS,NBA1",1980-81,55.432826,26.829268
3,Kareem Abdul-Jabbar,33.0,LAL,C,80.0,0.0,37.2,10.5,18.2,57.692308,0.0,0.0,0.0,10.5,18.2,57.692308,57.692308,5.3,6.9,76.811594,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,"MVP-3,AS,NBA1",1980-81,61.687700,38.875000
4,David Thompson,26.0,DEN,SG,77.0,0.0,34.0,9.5,18.8,50.531915,0.1,0.5,20.0,9.4,18.3,51.366120,50.797872,6.4,8.0,80.000000,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,No Awards,1980-81,57.123656,25.454545

In [9]:
print(combined_data.columns, "\n")
# Reorder Features
columns = ['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
           '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
           'TS%', 'EFF', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 
           'Awards', 'Season']

# Apply the new column order
combined_data = combined_data[columns]

# Print the columns and dataFrame
print(combined_data.columns, "\n")

combined_data.head(5)

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Awards',
       'Season', 'TS%', 'EFF'],
      dtype='object')

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'TS%', 'EFF', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF',
       'PTS', 'Awards', 'Season'],
      dtype='object')

,Player,Age,Team,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,TS%,EFF,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards,Season
0,Adrian Dantley,25.0,UTA,SF,80.0,0.0,42.7,11.4,20.3,56.157635,0.0,0.1,0.0,11.3,20.3,55.665025,56.157635,7.9,9.8,80.612245,62.367951,35.500000,2.4,4.0,6.4,4.0,1.4,0.2,3.5,3.1,30.7,"MVP-12,AS,NBA2",1980-81
1,Moses Malone,25.0,HOU,C,80.0,0.0,40.6,10.1,19.3,52.331606,0.0,0.0,0.0,10.1,19.3,52.331606,52.331606,7.6,10.1,75.247525,58.541105,39.625000,5.9,8.8,14.8,1.8,1.0,1.9,3.9,2.8,27.8,"MVP-4,AS,NBA2",1980-81
2,George Gervin,28.0,SAS,SG,82.0,82.0,33.7,10.4,21.1,49.289100,0.1,0.4,25.0,10.3,20.7,49.758454,49.526066,6.2,7.6,81.578947,55.432826,26.829268,1.5,3.6,5.1,3.2,1.1,0.7,3.1,2.6,27.1,"MVP-5,AS,NBA1",1980-81
3,Kareem Abdul-Jabbar,33.0,LAL,C,80.0,0.0,37.2,10.5,18.2,57.692308,0.0,0.0,0.0,10.5,18.2,57.692308,57.692308,5.3,6.9,76.811594,61.687700,38.875000,2.5,7.8,10.3,3.4,0.7,2.9,3.1,3.1,26.2,"MVP-3,AS,NBA1",1980-81
4,David Thompson,26.0,DEN,SG,77.0,0.0,34.0,9.5,18.8,50.531915,0.1,0.5,20.0,9.4,18.3,51.366120,50.797872,6.4,8.0,80.000000,57.123656,25.454545,1.4,2.3,3.7,3.0,0.7,0.8,3.2,3.0,25.5,No Awards,1980-81

In [10]:
# Adding Team Wins, Losses, and Win/Loss % columns to each player
import pandas as pd
team_win_data = pd.read_csv('../processed-data/prepared_team_win_data.csv')
# Check
team_win_data.head()

# Modify 'Season' values in combined_data  
combined_data['Season'] = combined_data['Season'].str.split('-').str[0]
# Check
combined_data.head() 

# See all unique values in combined_data['Team'], alphabetically, and all columns in team_win_data to merge correctly
print(sorted(combined_data['Team'].unique()), "\n")

# Extract the column names, convert to list, and exclude 'Season'
team_columns = list(team_win_data.columns.difference(['Season']))
print(team_columns, '\n')

# Drop players with multiTeam values in 'Team'
combined_data = combined_data[~combined_data['Team'].isin(['2TM', '3TM', '4TM', '5TM'])]
# Change Charlotte Hornets team abbreviations (CHO, CHA = CHO) 
combined_data['Team'] = combined_data['Team'].replace({'CHH': 'CHO', 'CHA': 'CHO'})
# Change Kansas City Kings to Sacramento Kings (KCK = SAC)
combined_data['Team'] = combined_data['Team'].replace({'KCK': 'SAC'})
# Change New Jersey Nets to Brooklyn Nets (NJN = BRK)
combined_data['Team'] = combined_data['Team'].replace({'NJN': 'BRK'})
# Change New Orleans/Oklahoma City Hornets to New Orleans Pelicans (NOK, NOH = NOP)
combined_data['Team'] = combined_data['Team'].replace({'NOK': 'NOP', 'NOH': 'NOP'})
# Change San Diego Clippers to Los Angeles Clippers (SDC = LAC)
combined_data['Team'] = combined_data['Team'].replace({'SDC': 'LAC'})
# Change Seattle SuperSonics to Oklahoma City Thunder (SEA = OKC)
combined_data['Team'] = combined_data['Team'].replace({'SEA': 'OKC'})
# Change Vancouver Grizzlies to Memphis Grizzlies (VAN = MEM)
combined_data['Team'] = combined_data['Team'].replace({'VAN': 'MEM'})
# Change Washington Bullets to Washington Wizards (WSB = WAS)
combined_data['Team'] = combined_data['Team'].replace({'WSB': 'WAS'})

print(sorted(combined_data['Team'].unique()))

['2TM', '3TM', '4TM', '5TM', 'ATL', 'BOS', 'BRK', 'CHA', 'CHH', 'CHI', 'CHO', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'KCK', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NJN', 'NOH', 'NOK', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHO', 'POR', 'SAC', 'SAS', 'SDC', 'SEA', 'TOR', 'UTA', 'VAN', 'WAS', 'WSB']

['ATL', 'BOS', 'BRK', 'CHI', 'CHO', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHO', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS']

['ATL', 'BOS', 'BRK', 'CHI', 'CHO', 'CLE', 'DAL', 'DEN', 'DET', 'GSW', 'HOU', 'IND', 'LAC', 'LAL', 'MEM', 'MIA', 'MIL', 'MIN', 'NOP', 'NYK', 'OKC', 'ORL', 'PHI', 'PHO', 'POR', 'SAC', 'SAS', 'TOR', 'UTA', 'WAS']

In [11]:
# Create a temporary DataFrame with only 'Season' and the relevant team win columns from team_win_data
team_wins_only = team_win_data.set_index('Season').stack().reset_index()
team_wins_only.columns = ['Season', 'Team', 'tW']

# Ensure both 'Season' columns have the same data type (int64)
combined_data['Season'] = combined_data['Season'].astype(int)
team_wins_only['Season'] = team_wins_only['Season'].astype(int)

# Merge combined_data with team_wins_only on 'Season' and 'Team'
merged_data = pd.merge(combined_data, team_wins_only, on=['Season', 'Team'], how='left')

# Check the 5 sample rows of the result
merged_data[['Player', 'Team', 'Season', 'tW']].sample(n=5)

               Player Team  Season    tW
176       Bob Elliott  BRK    1980  24.0
5796   Vernon Maxwell  PHI    1995  18.0
15699    Ronnie Price  LAL    2014  21.0
3858    David Wingate  SAS    1990  55.0
16473    Lou Williams  HOU    2016  55.0

In [12]:
# Add Team Games Played (tGP)

# Default tGP value
merged_data['tGP'] = 82

# 1998 Season / Lockout / 50 tGP
merged_data.loc[merged_data['Season'] == 1998, 'tGP'] = 50
# 2011 Season / Lockout / 66 tGP
merged_data.loc[merged_data['Season'] == 2011, 'tGP'] = 66
# 2012 Season / Boston Marathon Bombing / 81 tGP for BOS and IND
merged_data.loc[(merged_data['Season'] == 2012) & merged_data['Team'].isin(['IND', 'BOS']), 'tGP'] = 81
# 2020 Season / COVID / 72 tGP
merged_data.loc[merged_data['Season'] == 2020, 'tGP'] = 72

# 2019 Season - COVID adjustments
covid_teams = {
    64: ['MIN'],
    65: ['CHO', 'CHI', 'CLE', 'GSW'],
    66: ['NYK', 'DET'],
    67: ['ATL'],
    71: ['LAL', 'SAS'],
    72: ['TOR', 'BOS', 'BRK', 'WAS', 'LAC', 'HOU', 'OKC', 'UTA', 'SAC', 'NOP'],
    73: ['MIL', 'IND', 'MIA', 'PHI', 'ORL', 'DEN', 'MEM', 'PHO'],
    74: ['POR'],
    75: ['DAL']
}

# Apply the changes to 2019 season based on the team
for games, teams in covid_teams.items():
    merged_data.loc[(merged_data['Season'] == 2019) & (merged_data['Team'].isin(teams)), 'tGP'] = games

merged_data[merged_data['Season'] == 2019]

# Check the first few rows of the result
merged_data[['Player', 'Team', 'Season', 'tW', 'tGP']].sample(n=10)

# Sample 10 rows where Seasons are 1998, 2011, 2012, 2019, 2020
merged_data[(merged_data['Season'] == 2020) | 
            (merged_data['Season'] == 2011) |
            (merged_data['Season'] == 2012) | 
            (merged_data['Season'] == 2019) | 
            (merged_data['Season'] == 1998)][['Player', 'Team', 'Season', 'tW', 'tGP']].sample(n=10)

                 Player Team  Season    tW  tGP
7713      Trevor Winter  MIN    1998  25.0   50
18901     Darius Bazley  OKC    2020  22.0   72
7430    Calbert Cheaney  WAS    1998  18.0   50
18674     Chimezie Metu  SAS    2019  32.0   71
18814       Paul George  LAC    2020  47.0   72
7371         Grant Long  ATL    1998  31.0   50
13911  Chandler Parsons  HOU    2011  34.0   66
14534       Lavoy Allen  PHI    2012  34.0   82
19251      John Konchar  MEM    2020  38.0   72
18618    Treveon Graham  ATL    2019  20.0   67

In [13]:
# Add Team Games Lost (tL) and Team Win Percentage (tW%)
merged_data['tL'] = merged_data['tGP'] - merged_data['tW']
merged_data['tW%'] = (merged_data['tW'] / merged_data['tGP']).round(3)

# Remove decimals, Convert tGP, tW, and tL columns to integers
merged_data['tGP'] = merged_data['tGP'].astype(int)
merged_data['tW'] = merged_data['tW'].astype(int)
merged_data['tL'] = merged_data['tL'].astype(int)

# merged_data[['Player', 'Team', 'Season', 'tGP', 'tW', 'tL', 'tW%' ]].sample(n=10)
merged_data[(merged_data['Season'] == 2020) | 
            (merged_data['Season'] == 2011) |
            (merged_data['Season'] == 2012) | 
            (merged_data['Season'] == 2019) | 
            (merged_data['Season'] == 1998)][['Player', 'Team', 'Season', 'tGP', 'tW', 'tL', 'tW%']].sample(n=10)

                 Player Team  Season  tGP  tW  tL    tW%
13966      John Salmons  SAC    2011   66  22  44  0.333
14169    Sasha Pavlović  BOS    2011   66  39  27  0.591
14473   Thabo Sefolosha  OKC    2012   82  60  22  0.732
18447      Trevor Ariza  POR    2019   74  35  39  0.473
13756       Paul Pierce  BOS    2011   66  39  27  0.591
14333       Rajon Rondo  BOS    2012   81  41  40  0.506
19127  Dennis Smith Jr.  DET    2020   72  20  52  0.278
7412        Jim Jackson  POR    1998   50  35  15  0.700
19214        Marc Gasol  LAL    2020   72  42  30  0.583
13919    Tiago Splitter  SAS    2011   66  50  16  0.758

In [14]:
# Reorder columns before saving
merged_data = merged_data[['Player', 'Age', 'Team', 'Season', 'tGP', 'tW', 'tL', 'tW%', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%', 'TS%', 'EFF', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Awards']]
merged_data.sample(5)

,Player,Age,Team,Season,tGP,tW,tL,tW%,Pos,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,TS%,EFF,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
21027,Mãozinha Pereira,23.0,MEM,2023,82,27,55,0.329,SF,7.0,1.0,17.4,2.6,5.0,52.000000,0.7,1.9,36.842105,1.9,3.1,61.290323,59.000000,1.0,1.4,71.428571,61.431624,150.000000,1.6,3.7,5.3,0.3,0.9,0.6,0.7,1.4,6.9,No Awards
8405,Ron Harper,37.0,LAL,2000,82,56,26,0.683,PG,47.0,46.0,24.2,2.7,5.8,46.551724,0.4,1.5,26.666667,2.3,4.2,54.761905,50.000000,0.7,1.0,70.000000,52.083333,19.148936,1.0,2.6,3.5,2.4,0.8,0.5,1.3,1.5,6.5,No Awards
19852,DeAndre' Bembry,27.0,MIL,2021,82,51,31,0.622,SF,8.0,0.0,9.6,0.4,1.0,40.000000,0.0,0.0,0.000000,0.4,1.0,40.000000,40.000000,0.0,0.0,0.000000,40.000000,32.500000,0.5,0.9,1.4,0.8,0.3,0.0,0.1,1.1,0.8,No Awards
5444,Muggsy Bogues,30.0,CHO,1994,82,50,32,0.610,PG,78.0,78.0,33.7,4.5,9.4,47.872340,0.1,0.4,25.000000,4.4,9.0,48.888889,48.404255,2.1,2.3,91.304348,53.303880,22.564103,0.7,2.6,3.3,8.7,1.3,0.0,1.7,1.9,11.1,No Awards
16577,Tyreke Evans,27.0,SAC,2016,82,32,50,0.390,SF,14.0,6.0,22.4,4.2,10.2,41.176471,1.5,3.4,44.117647,2.7,6.8,39.705882,48.529412,1.7,2.4,70.833333,51.528074,75.714286,0.5,3.1,3.6,2.4,0.9,0.4,1.6,1.4,11.6,No Awards

In [15]:
# Check for missing values in 'tGP' column
missing_values = merged_data['tGP'].isnull().sum()

# Print the result
print(f"Number of missing values in 'tGP' column: {missing_values}")

Number of missing values in 'tGP' column: 0

In [16]:
# Code block for writing/saving processed data

# Save combined dataframe to processed data directory
processed_data_path = "../processed-data/combined_data.csv"
merged_data.to_csv(processed_data_path, index=False)
print(f"Data saved to: {processed_data_path}") # Confirmation

Data saved to: ../processed-data/combined_data.csv